# Generated by Django 3.2.6 on 2021-08-16 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postion_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('skills', models.TextField()),
                ('emp_percentage', models.TextField()),
                ('postion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comapny_profiles.postion')),
            ],
        ),
    ]
