# Generated by Django 3.2.6 on 2021-08-17 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comapny_profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='postion',
            new_name='postions',
        ),
    ]
