# Generated by Django 3.2.6 on 2021-08-17 09:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comapny_profiles', '0002_rename_postion_company_postions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postion',
            old_name='postion_name',
            new_name='employee',
        ),
        migrations.AddField(
            model_name='postion',
            name='manager',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
